services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"   # REST
      - "50051:50051" # gRPC
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      ENABLE_MODULES: "text2vec-openai"
      CLUSTER_HOSTNAME: "weaviate"

# execute: docker-compose up -d
# delete: docker-compose down

