# -------------------------------
# Standard RAG Configuration
# -------------------------------

# Splitter configuration
splitter:
  name: "recursive"        # Options: "recursive", "character", "token"
  chunk_size: 500          # For "recursive" and "character"
  chunk_overlap: 50        # For "recursive" and "character"
  separator: "\n\n"        # For "character" → options: "\n\n", "\n", " ", ""
  token_chunk_size: 256    # For "token"
  token_chunk_overlap: 20  # For "token"

# Embeddings configuration
embeddings:
  provider: "huggingface"  # Options: "huggingface", "openai", "cohere"
  model_name: "sentence-transformers/all-MiniLM-L6-v2"
  # model_name options for openai: "text-embedding-3-small"
  # model_name options for cohere: "embed-english-v3.0"

# Vectorstore configuration
vectorstore:
  name: "faiss"             # Options: "faiss", "chroma", "weaviate", "pinecone"
  persist_directory: "chroma-db"   # Only for Chroma
  index_name: "TestIndex"           # For Weaviate or Pinecone
  embeddings_dim: 384               # For Pinecone
  similarity_metric: "cosine"       # For Pinecone

# Retriever configuration
retriever:
  type: "dense"   # Options: "dense", "sparse", "hybrid"
  k: 5            # Number of top documents to retrieve per query

# Reranker config (only for rerank architecture)
reranker:
  model_name: "cross-encoder/ms-marco-MiniLM-L-6-v2"  # Options: any HuggingFace CrossEncoder
  top_k: 3                                           # Number of documents to keep after reranking


# Generator / LLM configuration
generator:
  provider: "openai"       # LLM provider: "openai", "anthropic", "gemini", "groq", "deepseek"
  model_name: "gpt-4o-mini" # Specific model name from provider
  max_tokens: 500           # Max tokens in output
  temperature: 0.6          # Creativity vs determinism (higher = more creative)
  top_p: 0.9                # Nucleus sampling (probability cutoff for token choices)
  timeout: 10               # Max time (seconds) to wait for response
  max_retries: 2            # Retry attempts if API call fails

